name: Find and Replace Href File Extension

on:
  workflow_dispatch
    
jobs:
  build:
  
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "This is a contrived test String used to test out the new GitHub Actions I am setting up."
          replace: "hey cool it worked!"
          regex: false
