name: Find and Replace Href File Extension

on:
  workflow_dispatch
    
jobs:
  deploy_on_pi:
    name: Deploy to Raspberry Pi Server
  
    runs-on: [self-hosted, linux, ARM]
    
    steps:
      - name: Checkout the main branch
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Change directory to Java Archive path and run
        run: |
          cd /home/pi/actions-runner/donau.ca_work/donau.ca/donau.ca/tools/Java/GitHubActionFindAndReplace/dist
          java -jar GitHubActionFindAndReplace.jar "/home/pi/actions-runner/donau.ca_work/donau.ca/donau.ca/www" ".html\" data-remove-file-extension=\"true\"" "\" data-remove-file-extension=\"true\""
